---
require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/**/*
    - tmp/**/*
    - node_modules/**/*

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/BlockComments:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
